2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Configure stats pid to 14269
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/.config/wandb/settings
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/settings
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_init.py:_log_setup():476] Logging user logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151001-2q95sm3f/logs/debug.log
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_init.py:_log_setup():477] Logging internal logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151001-2q95sm3f/logs/debug-internal.log
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f38b93bfd30>
2022-11-21 15:10:01,521 INFO    MainThread:14269 [wandb_init.py:init():516] calling init triggers
2022-11-21 15:10:01,522 INFO    MainThread:14269 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-21 15:10:01,522 INFO    MainThread:14269 [wandb_init.py:init():569] starting backend
2022-11-21 15:10:01,522 INFO    MainThread:14269 [wandb_init.py:init():573] setting up manager
2022-11-21 15:10:01,527 ERROR   MainThread:14269 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 170, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 35, in _svc_inform_init
    _pbmap_apply_dict(inform_init._settings_map, settings_dict)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_base.py", line 45, in _pbmap_apply_dict
    raise Exception("unsupported type")
Exception: unsupported type
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Configure stats pid to 14269
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/.config/wandb/settings
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/settings
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_init.py:_log_setup():476] Logging user logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151049-ejekogu4/logs/debug.log
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_init.py:_log_setup():477] Logging internal logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151049-ejekogu4/logs/debug-internal.log
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_init.py:init():516] calling init triggers
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_init.py:init():569] starting backend
2022-11-21 15:10:49,740 INFO    MainThread:14269 [wandb_init.py:init():573] setting up manager
2022-11-21 15:10:49,744 ERROR   MainThread:14269 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 170, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 35, in _svc_inform_init
    _pbmap_apply_dict(inform_init._settings_map, settings_dict)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_base.py", line 45, in _pbmap_apply_dict
    raise Exception("unsupported type")
Exception: unsupported type
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Configure stats pid to 14269
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/.config/wandb/settings
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/settings
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_init.py:_log_setup():476] Logging user logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151457-3rel1n6x/logs/debug.log
2022-11-21 15:14:57,883 INFO    MainThread:14269 [wandb_init.py:_log_setup():477] Logging internal logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151457-3rel1n6x/logs/debug-internal.log
2022-11-21 15:14:57,884 INFO    MainThread:14269 [wandb_init.py:init():516] calling init triggers
2022-11-21 15:14:57,884 INFO    MainThread:14269 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-21 15:14:57,884 INFO    MainThread:14269 [wandb_init.py:init():569] starting backend
2022-11-21 15:14:57,884 INFO    MainThread:14269 [wandb_init.py:init():573] setting up manager
2022-11-21 15:14:57,890 ERROR   MainThread:14269 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 170, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 35, in _svc_inform_init
    _pbmap_apply_dict(inform_init._settings_map, settings_dict)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_base.py", line 45, in _pbmap_apply_dict
    raise Exception("unsupported type")
Exception: unsupported type
2022-11-21 15:15:21,144 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Configure stats pid to 14269
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/.config/wandb/settings
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/settings
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_init.py:_log_setup():476] Logging user logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151521-3lsdw3f8/logs/debug.log
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_init.py:_log_setup():477] Logging internal logs to /home/murali/AIM-AnimationSoftwareWorkShop/week-3lec/wandb/run-20221121_151521-3lsdw3f8/logs/debug-internal.log
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_init.py:init():516] calling init triggers
2022-11-21 15:15:21,145 INFO    MainThread:14269 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-21 15:15:21,146 INFO    MainThread:14269 [wandb_init.py:init():569] starting backend
2022-11-21 15:15:21,146 INFO    MainThread:14269 [wandb_init.py:init():573] setting up manager
2022-11-21 15:15:21,152 ERROR   MainThread:14269 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 170, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 35, in _svc_inform_init
    _pbmap_apply_dict(inform_init._settings_map, settings_dict)
  File "/home/murali/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/service/service_base.py", line 45, in _pbmap_apply_dict
    raise Exception("unsupported type")
Exception: unsupported type
